#!/bin/bash

DOTFILES_DIR="/root/.init/dotfiles"

for dotfile in $(find $DOTFILES_DIR -maxdepth 1 ! -path $DOTFILES_DIR); do
  dotfile="${dotfile##*/}"
  rm -fr /root/$dotfile
  ln -fs /root/.init/dotfiles/$dotfile /root/$dotfile
done
